# main config
encoding: utf-8
timezone: America/Argentina/Buenos_Aires

# Dependencies
markdown:            kramdown
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:title/
#relative_permalinks: true

# Setup
title:               "blog.ngen.com.ar"
tagline:             "Crónica de una instalación anunciada"
description:         "Offering technical posts and how-to articles from an IT pro specializing in networking, virtualization, & cloud computing"
url:                 https://blog.ngen.com.ar
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Carlos Miranda (Mstaaravin) 
  url:               https://twitter.com/mstaaravin
  email:             mstaaravin@gmail.com
  github:            Mstaaravin
  twitter:           Mstaaravin
  linkedin:			 cmngen
#  rss:				 yes

#Your disqus shortname, entering this will enable commenting on posts
disqus: blogngencomar

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-37994253-2

# Custom vars
version:             1.2.0

# Exclude Ruby gem stuff
exclude:             ["vendor"]

jekyll-mentions: https://twitter.com
  
# Gems
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-mentions
theme: jekyll-theme-hacker
